### ISSUE TITLE
Tradução Português Brasileiro 

### ISSUE THREAD

**Issue by CoffeDaCat** [eFurry/android-translation#18]

**Comment by Malamutedog** [comment]
pt-rBR has been added, check the progress at [https://github.com/eFurry/android-translation/actions/runs/6901962960/job/18777758613](https://github.com/eFurry/android-translation/actions/runs/6901962960/job/18777758613)

**Comment by Malamutedog** [comment]
Can you check the file https://github.com/eFurry/android-translation/pull/19/files
and add comments with the correct translation to lines that need changes? @CoffeDaCat
